### PR TITLE
Moved client files to /client

### PR DESCRIPTION
**Pull request by alexnsolo**

### CODE REVIEW

**Comment by jbauschatz** [comment]
@civilframe how is it if we leave index.html in the root folder for now? I don't know how to point the github pages into the client folder yet...

**Comment by alexnsolo** [comment]
Well, then express would have to serve up the entire root folder, putting us back to square one. How about we hold off merging until we can setup a different hosting solution that uses express?

**Comment by forana** [comment]
(philosophy tangent: .gitignore signals to other developers "these are files that I never ever want to see in this repo")

**Comment by forana** [comment]
Temporary to get around the gh-pages thing: http://en.wikipedia.org/wiki/Meta_refresh

**Comment by jbauschatz** [comment]
Sure. The reason I thought to keep it out is that if each developer uses
different IDE the .gitignore becomes flooded with everybody's project files
and such. Seems like it could become a mess, and less of a "signal". But I
get it.

On Mon, Oct 20, 2014 at 9:36 AM, forana notifications@github.com wrote:

> (philosophy tangent: .gitignore signals to other developers "these are
> files that I never ever want to see in this repo")
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ConchordanceProject/ConchordanceWeb/pull/70#issuecomment-59767353
> .

## 

Sláinte Mhath,
John Charles

**Comment by forana** [comment]
java default doesn't include IDE files: https://github.com/github/gitignore/blob/master/Java.gitignore

(I usually include them, but I'm very guilty of using .gitignore instead of `--assume-unchanged` because it's easier :smile: )

**Comment by jbauschatz** [comment]
I think I understand the standard now. The .gitignore includes project-generated artifacts but not external files. Developer's are responsible for keeping their own .project/etc out using the --assume-unchanged.

**Comment by alexnsolo** [comment]
This PR is now obsolete by the "Log in, log out" one.

**Pull request closed without merging**
